# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="re5et"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often to auto-update? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to the command execution time stamp shown 
# in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git common-aliases cp golang history last-working-dir screen)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH=$HOME/bin:/usr/local/bin:/usr/local/go/bin:$PATH
export GOPATH=$HOME/gocode
export PATH=$PATH:$GOPATH/bin #golang
export PATH=/usr/bin/node:$PATH #nodejs
# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/dsa_id"
#git
alias gs='git status'
alias gc='git commit -v -a'
alias ga='git add .'
#screen
alias sls="screen -ls" #list screens
alias sd="screen -dmS" #screen in daemon mode
alias sr="screen -x" #connect to screen w/ multi allowed
alias ss="screen -S" #create screen with name
alias slsa='sudo ls -laR /var/run/screen/'
#zsh
alias c='clear'
alias q='exit'
alias f='sudo find / -name'
alias ds='du -hs * | sort -h'
alias rm='/bin/rm' #undo rm -i from plugin
alias ln='echo "ln -s {source} {destination}"; ln -s'
alias cp='/bin/cp' #remove -i from plugin
# sudo apt-get install {in}
alias in='sudo apt-get install'
# sudo apt-cache search {se}
alias se='sudo apt-cache search'
# sudo apt-cache policy {po}
alias po='sudo apt-cache policy'
function ppa() {sudo add-apt-repository ppa:$@}
alias ppal='grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*'
#highly custom
alias -g C='| xclip -selection c'
alias derooy-reinstall-zsh='yes | cp ~/p/dotfiles/templates/zshrc ~/.zshrc; source ~/.zshrc'
cpy() {
    cpy="$(readlink -f $*)"
    echo $cpy
}
pst() {
	cp $cpy "$*"
}
cp() {
	src="$1"
	dest="$2"
	echo "cp \e[1;34m$src \e[0mto \e[1;36m$dest\e[0m"
	rsync --archive --human-readable --stats --progress $src $dest
	echo "cp \e[1;34m$src \e[0mto \e[1;36m$dest\e[0m"
}
# \e[0;31m
# \e[1;34
# \e[1;36