ZSH=$HOME/.oh-my-zsh
ZSH_THEME="re5et"
DISABLE_AUTO_UPDATE="true"
# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"
plugins=(git common-aliases cp golang history last-working-dir screen)
source $ZSH/oh-my-zsh.sh
export PATH=$HOME/bin:/usr/local/bin:/usr/local/go/bin:$PATH
export GOPATH=$HOME/gocode
export PATH=$PATH:$GOPATH/bin #golang
export PATH=/usr/bin/node:$PATH #nodejs
export EDITOR='vim'
export SSH_KEY_PATH="~/.ssh/dsa_id"

# ------------------- My personal extras

#git
alias gs='git status'
alias gc='git commit -v -a'
alias ga='git add .'
#screen
alias sls="screen -ls" #list screens
alias sd="screen -dmS" #screen in daemon mode
alias sr="screen -x" #connect to screen w/ multi allowed
alias ss="screen -S" #create screen with name
alias slsa='sudo ls -laR /var/run/screen/'
#zsh
alias c='clear'
alias q='exit'
alias f='sudo find / -name'
alias ds='du -hs * | sort -h'
alias rm='/bin/rm' #undo rm -i from plugin
alias ln='echo "ln -s {source} {destination}"; ln -s'
alias cp='/bin/cp' #remove -i from plugin
# sudo apt-get install {in}
alias matt@corbeti.org='ssh matt@corbeti.org -p 21976'
alias matt@xbmc='ssh matt@192.168.1.100'
alias matt@btc='ssh matt@192.168.1.30'


#apt-get
alias in='sudo apt-get install'
alias se='sudo apt-cache search'
alias po='sudo apt-cache policy'
alias upt='sudo apt-get update'
alias upd='sudo apt-get upgrade'
function ppa() {sudo add-apt-repository ppa:$@}
alias ppal='grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*'

#highly custom
alias todo='subl ~/s/Dropbox/Todo.md'
alias derooy-reinstall-zsh='yes | cp ~/p/dotfiles/templates/zshrc ~/.zshrc; source ~/.zshrc'
cb() { # alias -g C='| tee /dev/tty | tr -d '\n' | xclip -selection clipboard'
  local _scs_col="\e[0;32m"; local _wrn_col='\e[1;31m'; local _trn_col='\e[0;33m'
  # Check that xclip is installed.
  if ! type xclip > /dev/null 2>&1; then
    echo -e "$_wrn_col""You must have the 'xclip' program installed.\e[0m"
  # Check user is not root (root doesn't have access to user xorg server)
  elif [[ "$USER" == "root" ]]; then
    echo -e "$_wrn_col""Must be regular user (not root) to copy a file to the clipboard.\e[0m"
  else
    # If no tty, data should be available on stdin
    if ! [[ "$( tty )" == /dev/* ]]; then
      input="$(< /dev/stdin)"
    # Else, fetch input from params
    else
      input="$*"
    fi
    if [ -z "$input" ]; then  # If no input, print usage message.
      echo "Copies a string to the clipboard."
      echo "Usage: cb <string>"
      echo "       echo <string> | cb"
    else
      # Copy input to clipboard
      echo -n "$input" | xclip -selection c
      # Truncate text for status
      if [ ${#input} -gt 80 ]; then input="$(echo $input | cut -c1-80)$_trn_col...\e[0m"; fi
      # Print status.
      echo -e "$_scs_col""Copied to clipboard:\e[0m $input"
    fi
  fi
}
cpy() {
    cpy="$(readlink -f $*)"
    echo $cpy
}

pst() {
	cp $cpy "$*"
}
pwd() {
	if [ $# -eq 0 ]; then
		readlink -f .
	else
		readlink -f "$*"
	fi
}
cp() {
	src="$1"
	dest="$2"
	echo "cp \e[1;34m$src \e[0mto \e[1;36m$dest\e[0m"
	rsync --archive --human-readable --stats --progress $src $dest
	echo "cp \e[1;34m$src \e[0mto \e[1;36m$dest\e[0m"
}
